pub mod squares_of_sorted_array_977;
pub mod count_elements_with_maximum_frequency_3005;
pub mod minimum_common_value_2540;
pub mod intersect_of_two_arrays_349;
pub mod find_the_pivot_integer_2485;
pub mod number_of_students_unable_to_eat_lunch_1700;
pub mod time_needed_to_buy_tickets_2073;
pub mod island_perimeter_463;
pub mod relative_ranks_506;
